version: "3.9"

services:

  register-device:
    image: lmbd-digital-push-notifications
    container_name: register-device
    # command: ["register-device"]
    environment:
      - LAMBDA_BIN=register-device
    env_file:
      - .env
    # entrypoint: ["/bin/sh", "-c", "cp /var/task/$LAMBDA_BIN /var/task/bootstrap && exec /var/task/bootstrap"]
    volumes:
      - ./bin:/var/task
      - ./.env:/var/task/.env:ro
    ports:
      - "9001:8080"

  update-device:
    image: lmbd-digital-push-notifications
    container_name: update-device
    # command: ["register-device"]
    environment:
      - LAMBDA_BIN=update-device
    env_file:
      - .env
    # entrypoint: ["/bin/sh", "-c", "cp /var/task/$LAMBDA_BIN /var/task/bootstrap && exec /var/task/bootstrap"]
    volumes:
      - ./bin:/var/task
      - ./.env:/var/task/.env:ro
    ports:
      - "9002:8080"

  device-subscribe:
    image: lmbd-digital-push-notifications
    container_name: device-subscribe
    # command: ["device-subscribe"]
    environment:
      - LAMBDA_BIN=device-subscribe
    env_file:
      - .env
    # entrypoint: ["/bin/sh", "-c", "cp /var/task/$LAMBDA_BIN /var/task/bootstrap && exec /var/task/bootstrap"]
    volumes:
      - ./bin:/var/task
      - ./.env:/var/task/.env:ro
    ports:
      - "9003:8080"

  device-unsubscribe:
    image: lmbd-digital-push-notifications
    container_name: device-unsubscribe
    # command: ["device-unsubscribe"]
    environment:
      - LAMBDA_BIN=device-unsubscribe
    env_file:
      - .env
    # entrypoint: ["/bin/sh", "-c", "cp /var/task/$LAMBDA_BIN /var/task/bootstrap && exec /var/task/bootstrap"]
    volumes:
      - ./bin:/var/task
      - ./.env:/var/task/.env:ro
    ports:
      - "9004:8080"

  # publish-notification:
  #   image: lmbd-digital-push-notifications
  #   container_name: publish-notification
  #   command: ["publish-notification"]
  #   ports:
  #     - "9004:8080"

  # postgres:
  #   image: postgres:16
  #   container_name: postgres_db
  #   # restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: push_notifications
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:7
  #   container_name: redis_cache
  #   # restart: always
  #   ports:
  #     - "6379:6379"
  #   command: ["redis-server", "--appendonly", "yes"]
  #   volumes:
  #     - redis_data:/data

  
  # dynamodb-local:
  #   image: amazon/dynamodb-local:latest
  #   container_name: dynamodb-local
  #   ports:
  #     - "8000:8000"
  #   command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
  #   working_dir: /home/dynamodblocal
  #   volumes:
  #     - dynamodb_data:/home/dynamodblocal/data
  #   restart: unless-stopped


# volumes:
  # dynamodb_data:
  # postgres_data:
  # redis_data: