version: "3.9"

services:

  register-device:
    image: lmbd-digital-push-notifications
    container_name: register-device
    # command: ["register-device"]
    environment:
      - LAMBDA_BIN=register-device
      - AWS_PROFILE=digital-dev-diego
      - AWS_REGION=us-east-1
    env_file:
      - .env
    volumes:
      - ./bin:/var/task
      - ./.env:/var/task/.env:ro
      - ~/.aws:/root/.aws:ro
    ports:
      - "9001:8080"

  update-device:
    image: lmbd-digital-push-notifications
    container_name: update-device
    # command: ["register-device"]
    environment:
      - LAMBDA_BIN=update-device
      - AWS_PROFILE=digital-dev-diego
      - AWS_REGION=us-east-1
    env_file:
      - .env
    volumes:
      - ./bin:/var/task
      - ./.env:/var/task/.env:ro
      - ~/.aws:/root/.aws:ro
    ports:
      - "9002:8080"

  device-subscribe:
    image: lmbd-digital-push-notifications
    container_name: device-subscribe
    # command: ["device-subscribe"]
    environment:
      - LAMBDA_BIN=device-subscribe
      - AWS_PROFILE=digital-dev-diego
      - AWS_REGION=us-east-1
    env_file:
      - .env
    volumes:
      - ./bin:/var/task
      - ./.env:/var/task/.env:ro
      - ~/.aws:/root/.aws:ro
    ports:
      - "9003:8080"

  device-unsubscribe:
    image: lmbd-digital-push-notifications
    container_name: device-unsubscribe
    # command: ["device-unsubscribe"]
    environment:
      - LAMBDA_BIN=device-unsubscribe
      - AWS_PROFILE=digital-dev-diego
      - AWS_REGION=us-east-1
    env_file:
      - .env
    volumes:
      - ./bin:/var/task
      - ./.env:/var/task/.env:ro
      - ~/.aws:/root/.aws:ro
    ports:
      - "9004:8080"

  publish-notification:
    image: lmbd-digital-push-notifications
    container_name: publish-notification
    # command: ["publish-notification"]
    environment:
      - LAMBDA_BIN=publish-notification
      - AWS_PROFILE=digital-dev-diego
      - AWS_REGION=us-east-1
    env_file:
      - .env
    volumes:
      - ./bin:/var/task
      - ./.env:/var/task/.env:ro
      - ~/.aws:/root/.aws:ro
    ports:
      - "9005:8080"